# Generated by Django 3.2.3 on 2021-09-23 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0006_auto_20210922_2330'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderDetails',
        ),
    ]
