# Generated by Django 3.2.3 on 2021-09-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0008_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='place',
            field=models.IntegerField(default=0),
        ),
    ]
