# Generated by Django 3.1.3 on 2021-09-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0010_auto_20210923_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.FloatField(default=0),
        ),
    ]
