# Generated by Django 3.1.3 on 2021-09-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0011_order_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mode',
            field=models.IntegerField(default=0),
        ),
    ]
