# Generated by Django 3.1.3 on 2021-09-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0012_order_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='place',
        ),
        migrations.AddField(
            model_name='product',
            name='paid',
            field=models.FloatField(default=0),
        ),
    ]
