# Generated by Django 3.2.3 on 2021-09-28 21:31

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0014_auto_20210928_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='echeance',
            name='dateEcheance',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 28, 21, 31, 30, 288087, tzinfo=utc)),
        ),
    ]
