# Generated by Django 3.2.3 on 2021-09-28 22:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0015_auto_20210928_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='prix_achat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='echeance',
            name='dateEcheance',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 28, 22, 12, 19, 852716, tzinfo=utc)),
        ),
    ]
